### ISSUE TITLE
Rename `Sample1ofn`

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp.Tutorial#4]
Remove `ofn` from project/solution files. (Update any reference materials, e.g. `codeproject` article).

**Comment by Dirkster99** [comment]
Yes you can rename and update the article - I've set you as co-author. Thanks

**Comment by amaitland** [comment]
I'm having trouble logging into code project, so will try again later. I've updated the projects to `39.0.0` and renamed the solution.

**Comment by Dirkster99** [comment]
I was able to log into CodeProject so I renamed the occurences of Sample1ofn into Sample1 in the first article (there were only 2 such edits).

**Comment by amaitland** [comment]
Great, thanks :+1: 

When I sort out what's going on with the codeproject login I'll go over the second article again.
