### ISSUE TITLE
cefsharp/43    why i can't find IResourceHandlerFactory.RegisterHandler

### ISSUE THREAD

**Issue by wangliuzheng** [cefsharp/CefSharp.Tutorial#7]
why delete below two methods ,    
 void RegisterHandler(string url, ResourceHandler handler);

        void UnregisterHandler(string url);

how i can loadhtml / loadstring to ChromiumWebBrowser ?????

**Comment by amaitland** [comment]
> why delete below two methods ,

The `API` was refactored to be more generic, much of the `ResourceHandler` and `SchemeHandler` code is now shared between the two.

You can of course implement your own `IResourceHandlerFactory` or you can continue to use the `DefaultResourceHandlerFactory` and simply cast it.

https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp/WebBrowserExtensions.cs#L254

**Comment by wangliuzheng** [comment]
@amaitland  thank you ....
