### ISSUE TITLE
Unable to open CefSharp source code in VS 2015

### ISSUE THREAD

**Issue by nagesh2501** [cefsharp/CefSharp.Tutorial#9]
Hi,

I am unable to open CefSharp source code in VS 2015. I am getting the following error.

"Project 'CefSharp.BrowserSubprocess.Core' could not be loaded because it's missing install components. To fix this launch Visual Studio setup with the following selections:
Install Visual C++ 2015 Tools for Windows Desktop"

I am using VS 2015. Also  I have Microsoft Visual C++ 2015 Redistributable component installed.

**Comment by amaitland** [comment]
This project hasn't been updated in over a year. It's based on a version of `CefSharp` that requires `VC++ 2012`.

If you need a basic working example then checkout https://github.com/cefsharp/CefSharp.MinimalExample

**Comment by nagesh2501** [comment]
I am trying to reference a X86/X64 version of CefSharp but it is not letting me do. I understand that it currently does not support AnyCPU settings. But our project is required to be run on any CPU so we cannot change the configurations to a specific platform. Is there any workaround for this?

This is quite urgent for us. A quick turn around would be of great help.

**Comment by amaitland** [comment]
I've updated the `Readme.md` to notify users this project is no longer maintained.

If you require support the place to ask questions is https://gitter.im/cefsharp/CefSharp#
